kind: pipeline
name: chart

steps:
- name: build
  image: banzaicloud/drone-kaniko:0.5.1
  settings:
    repo: ann17/chart
    auto_tag: true
    username:
      from_secret: username
    password:
      from_secret: password
- name: build-gv
  image: banzaicloud/drone-kaniko:0.6.0
  settings:
    repo: ann17/chart-gv
    auto_tag: true
    username:
      from_secret: username
    password:
      from_secret: password
